### ISSUE TITLE
[Bug] Error thrown on 0.2.0

### ISSUE THREAD

**Issue by anhgelus** [msmp-mc/altered-respawn#6]
Stacktrace:
```
Could not pass event EntityDamageByEntityEvent to AlteredRespawn v0.1.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:263) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1071) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:938) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:887) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1105) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2045) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1028) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1349) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:935) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:979) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityInsentient.z(EntityInsentient.java:1615) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.monster.EntityZombie.z(EntityZombie.java:347) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.a(SourceFile:152) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.e(SourceFile:144) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.ai.goal.PathfinderGoalZombieAttack.e(SourceFile:28) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(SourceFile:65) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.a(SourceFile:120) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.a(SourceFile:111) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityInsentient.eY(EntityInsentient.java:887) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityLiving.b_(EntityLiving.java:3121) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityInsentient.b_(EntityInsentient.java:657) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.monster.EntityMonster.b_(SourceFile:44) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.monster.EntityZombie.b_(EntityZombie.java:264) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:2852) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.EntityInsentient.l(EntityInsentient.java:419) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.entity.monster.EntityZombie.l(EntityZombie.java:234) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:847) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.level.World.a(World.java:689) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.level.WorldServer.lambda$9(WorldServer.java:425) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:405) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 6.0(20.0)
	at org.bukkit.craftbukkit.v1_19_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:117) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]
	at world.anhgelus.msmp.alteredrespawn.api.Stack$deathEvent$1.invoke(Stack.kt:47) ~[?:?]
	at world.anhgelus.msmp.alteredrespawn.api.Stack$deathEvent$1.invoke(Stack.kt:44) ~[?:?]
	at world.anhgelus.msmp.msmpcore.player.MPlayer.died(MPlayer.kt:112) ~[?:?]
	at world.anhgelus.msmp.alteredrespawn.api.Stack.deathEvent(Stack.kt:44) ~[?:?]
	at world.anhgelus.msmp.alteredrespawn.listener.RegisterListener.onDamage(RegisterListener.kt:14) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 40 more
```

Seems like to be linked with a previous [bug](https://github.com/msmp-mc/msmp-core/issues/4) in MSMPCore

**Comment by anhgelus** [comment]
More investigation is required to find if this bug comes from MSMPCore or from AlteredRespawn.

**Comment by Akik4** [comment]
Come from MSMPCore
```
	at world.anhgelus.msmp.msmpcore.player.MPlayer.died(MPlayer.kt:112) ~[?:?]
	at world.anhgelus.msmp.alteredrespawn.api.Stack.deathEvent(Stack.kt:44) ~[?:?]
```

**Comment by anhgelus** [comment]
Do you check the error in details?

Is it linked with a last issue in the MSMPCore ?

**Comment by Akik4** [comment]
Yes I see 
Maybe i forgot one line that can be true

**Comment by anhgelus** [comment]
Should we reopen this issue?

**Comment by Akik4** [comment]
Finnaly nop i think you've just didn't rebuild it and so you didn't get the fix

**Comment by Akik4** [comment]
So like i said no needed maybe you just forgot to rebuild it after fix

**Comment by Akik4** [comment]
Already fixed

**Comment by anhgelus** [comment]
Not fixed, comes from AlteredRespawn

**Comment by Akik4** [comment]
Error where in DeathEvent forgot to apply MaxLife when set health to a player

**Comment by Akik4** [comment]
Fixed
